---
driver: docker
driver_config:
  use_sudo: false
  forward: 4440:4440

platforms:
  - name: debian
    driver_config:
      image: debian:latest
      platform: debian
      require_chef_omnibus: false
      provision_command:
        - apt-get clean
        - apt-get update
        - apt-get install -y sudo openssh-server openssh-client debianutils curl openjdk-7-jdk
        - if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash kitchen; fi
        - echo kitchen:kitchen | chpasswd
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        - mkdir -p /etc/sudoers.d
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/kitchen
        - chmod 0440 /etc/sudoers.d/kitchen
        - mkdir -p /var/rundeck/jobs/nested
        - echo -e "<joblist>\n\
            <job>\n\
              <sequence keepgoing='false' strategy='node-first'>\n\
                <command>\n\
                  <exec>echo simple-job</exec>\n\
                </command>\n\
              </sequence>\n\
              <loglevel>INFO</loglevel>\n\
              <name>simple-job</name>\n\
              <description></description>\n\
            </job>\n\
          </joblist>" > /var/rundeck/jobs/simple-job.xml
        - echo -e "<joblist>\n\
            <job>\n\
              <sequence keepgoing='false' strategy='node-first'>\n\
                <command>\n\
                  <exec>echo nested-job</exec>\n\
                </command>\n\
              </sequence>\n\
              <loglevel>INFO</loglevel>\n\
              <name>job</name>\n\
              <description></description>\n\
              <group>nested</group>\n\
            </job>\n\
          </joblist>" > /var/rundeck/jobs/nested/job.xml
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
      platform: ubuntu
      require_chef_omnibus: false
      provision_command:
        - apt-get clean
        - apt-get update
        - apt-get install -y sudo openssh-server openssh-client debianutils curl openjdk-7-jdk
        - if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash kitchen; fi
        - echo kitchen:kitchen | chpasswd
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        - mkdir -p /etc/sudoers.d
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/kitchen
        - chmod 0440 /etc/sudoers.d/kitchen
        - mkdir -p /var/rundeck/jobs/nested
        - echo -e "<joblist>\n\
          <job>\n\
            <sequence keepgoing='false' strategy='node-first'>\n\
              <command>\n\
                <exec>echo simple-job</exec>\n\
              </command>\n\
            </sequence>\n\
            <loglevel>INFO</loglevel>\n\
            <name>simple-job</name>\n\
            <description></description>\n\
          </job>\n\
          </joblist>" > /var/rundeck/jobs/simple-job.xml
        - echo -e "<joblist>\n\
          <job>\n\
            <sequence keepgoing='false' strategy='node-first'>\n\
              <command>\n\
                <exec>echo nested-job</exec>\n\
              </command>\n\
            </sequence>\n\
            <loglevel>INFO</loglevel>\n\
            <name>job</name>\n\
            <description></description>\n\
            <group>nested</group>\n\
          </job>\n\
          </joblist>" > /var/rundeck/jobs/nested/job.xml
  - name: centos-6.6
    driver_config:
      image: centos:6.6
      platform: centos
      require_chef_omnibus: false
      provision_command:
        - yum clean all
        - apt-get update
        - yum install -y sudo openssh-server openssh-clients which curl java-1.7.0-openjdk
        - ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
        - ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
        - if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash kitchen; fi
        - echo kitchen:kitchen | chpasswd
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        - mkdir -p /etc/sudoers.d
        - echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/kitchen
        - chmod 0440 /etc/sudoers.d/kitchen
        - mkdir -p /var/rundeck/jobs/nested
        - echo -e "<joblist>\n\
            <job>\n\
              <sequence keepgoing='false' strategy='node-first'>\n\
                <command>\n\
                  <exec>echo simple-job</exec>\n\
                </command>\n\
              </sequence>\n\
              <loglevel>INFO</loglevel>\n\
              <name>simple-job</name>\n\
              <description></description>\n\
            </job>\n\
          </joblist>" > /var/rundeck/jobs/simple-job.xml
        - echo -e "<joblist>\n\
          <job>\n\
            <sequence keepgoing='false' strategy='node-first'>\n\
              <command>\n\
                <exec>echo nested-job</exec>\n\
              </command>\n\
            </sequence>\n\
            <loglevel>INFO</loglevel>\n\
            <name>job</name>\n\
            <description></description>\n\
            <group>nested</group>\n\
          </job>\n\
          </joblist>" > /var/rundeck/jobs/nested/job.xml

provisioner:
  name: salt_solo
  formula: rundeck
  state_top:
    base:
      '*':
        - rundeck
  pillars:
    top.sls:
      base:
        '*':
          - rundeck
    rundeck.sls:

suites:
  - name: default
  - name: config
    provisioner:
      pillars:
        rundeck.sls:
          rundeck:
            config:
              host: rundeck.local
              port: 80
              projects:
                storage: db
                dir: /home/rundeck/projects
                resources_file: resources.yml
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
              user:
                password: passwd
                groups:
                  - user
  - name: projects
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
      pillars:
        rundeck.sls:
          rundeck:
            projects:
              default:
              directory:
                resources:
                  - source: directory
                    directory: /var/rundeck/projects/${project.name}/etc/resources
              script:
                resources:
                  - source: script
                    script: /usr/bin/rd-jobs
                  - source: script
                    format: resourceyaml
                    script: /usr/bin/rd-queue
                    interpreter: /bin/sh
                    args: nodes
                    quote_interpreter_args: True
              url:
                resources:
                  - source: url
                    url: http://localhost/nodes.xml
                  - source: url
                    url: http://localhost/nodes2.xml
                    timeout: 1800
                    cache: False
              stub:
                resources:
                  - source: stub
                  - source: stub
                    prefix: fake
                    suffix: really
                    count: 2
                    tags: fake
              pillar:
                resources:
                  - source: pillar
                    nodes:
                      rundeck-server:
                        hostname: 127.0.0.1
                        username: rundeck
                      another-server:
                        hostname: 127.0.0.2
                        username: admin
                        description: Another server
                        tags: server,test
                        osFamily: unix
                        osArch: amd64
                        osName: Linux
                        osVersion: 3.16.0-0.bpo.4-amd64
                        custom: attribute
                      server-with-tags-list:
                        hostname: 127.0.0.3
                        username: user
                        tags:
                          - dev
                          - proto
  - name: jobs
    provisioner:
      state_top:
        base:
          '*':
            - rundeck
            - rundeck.projects
            - rundeck.jobs
      pillars:
        rundeck.sls:
          rundeck:
            users:
              admin:
                password: admin
                groups:
                  - user
                  - admin
            projects:
              my-project:
            jobs:
              map:
                my-project:
                  - simple-job
                  - nested/job
